#!/bin/bash
set +x
postgres -D $PGDATA -k /tmp 2>/dev/null&
postback=$!

set -e
project=YaKasserole

if [ -d django ];
then
  echo -e '\e[1;36mmise à jour de Django:\e[0m'
  cd django && git pull && cd -;
else
  echo -e '\e[1;32mInstallation de Django:\e[0m'
  git clone git://github.com/django/django.git
fi

# Install django and his modules
pip install --user -e django/ >/dev/null
pip install --user -r setup/REQUIREMENT.txt >/dev/null

#Correct unstable versions
to_modify="$HOME/.local/lib/python3.6/site-packages/payments/models.py"
if [ ! -f "$to_modify" ]; then
  to_modify="/usr/local/lib/python3.6/site-packages/payments/models.py"
fi

sed -r 's/(from )(.*)( import reverse)/\1django.urls\3/' "$to_modify" > /tmp/tmp
cat /tmp/tmp > "$to_modify"

#Setup Users
psql -h localhost postgres -f setup/setup_user.sql

#Install new project if it doesn't exist
if [ ! -d "$project" ]; then
  ~/.local/bin/django-admin startproject "$project"
  cd "$project"
fi

#Install different app
apps=('community' 'recette' 'atelier' 'comptes')
cd "$project"
set +e
find . -name 'migrations' -exec rm -rf {} \; 2>/dev/null
set -e
for i in "${apps[@]}"; do
  if [ ! -d "$i" ]; then
    python manage.py startapp $i
  fi
done

for i in "${apps[@]}"; do
  python manage.py makemigrations $i
  python manage.py migrate $i
done
python manage.py migrate

#enter admin for user
echo -e '\e[1;36mInitialisation des utilisateurs et des groupes:\e[0m'
python manage.py shell < ../setup/group.py

#add default recettes
echo -e '\e[1;36mchargement des outils de recette de base:\e[0m'
python manage.py loaddata ../setup/fixtures/recettes.yaml
echo -e '\e[1;36mchargement des outils de ateliers de base:\e[0m'
python manage.py loaddata ../setup/fixtures/ateliers.yaml

kill $postback

