#!/bin/bash

set -e

if [ $# -eq 1 ] && [ "$1" == "test" ]; then
  rm -rf test
  tar -cjf YaKasserole-golbl_a.tar.bz2 --exclude django --exclude migration --exclude "*.bz2" --exclude "*.log" --exclude "*/migrations" .
  echo "Tar Done"
  mkdir test
  mv YaKasserole-golbl_a.tar.bz2 test
  cd test
  tar -xjf YaKasserole-golbl_a.tar.bz2
  echo "Untar Done"
  ./bootstrap
  sleep 1s
  ./test.sh
  sleep 1s
  ./benchmark
  echo -n "mda to put:"
  md5sum YaKasserole-golbl_a.tar.bz2 | cut -d ' ' -f1
  rm -rf test YaKasserole-golbl_a.bz2
  echo "The tar test works"
else
  tar -cjf YaKasserole-golbl_a.tar.bz2 --exclude django --exclude migration --exclude "*.bz2" --exclude "*.log" --exclude "*/migrations" .
  md5sum YaKasserole-golbl_a.tar.bz2 | cut -d ' ' -f1
fi
